package roomscheduleryqd5143;


import java.sql.Date;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat; 

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acv
 */
public class RoomSchedulerFrame extends javax.swing.JFrame
{

    
    /**
     * Creates new form RoomSchedulerFrame
     */
    public RoomSchedulerFrame()
    {
        initComponents();
        // slider doesnt slide like it should I use it like a textbox and enter manually
        // Load the combo boxes with data.
        rebuildFacultyComboBoxes();
        rebuildDateComboBoxes();
        rebuildRoomComboBoxes();
    }
    
    public void rebuildFacultyComboBoxes()
    {
        reserveFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray())); 
        FacultyjComboBox2.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray())); 
        FacultyStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
    }
    
    public void rebuildDateComboBoxes(){DateBox1.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
    DatejComboBox2.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
    DateforReservationjComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
    }
   
    public void rebuildRoomComboBoxes(){DropRoomjComboBox.setModel(new javax.swing.DefaultComboBoxModel(RoomQueries.getAllRooms().toArray()));
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        waitlistPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addFacultyTextField = new javax.swing.JTextField();
        addFacultyButton = new javax.swing.JButton();
        addFacultyStatusLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        DatesOfReservationCombobox = new javax.swing.JPanel();
        displayWaitlistButton = new javax.swing.JButton();
        DisplayReservationsButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DateBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputTextArea = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        RoomNamejTextField1 = new javax.swing.JTextField();
        RoomSeatsjTextField = new javax.swing.JTextField();
        AddRoomjButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AddRoomjTextArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        DropRoomjComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        DropRoomjButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DropRoomjTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        FacultyjComboBox2 = new javax.swing.JComboBox();
        DatejComboBox2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CancelReservationJbutton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CancelTextArea = new javax.swing.JTextArea();
        CancelWaitlistjButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        FacultyStatusComboBox = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Status2TextArea = new javax.swing.JTextArea();
        Status2jButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reserveFacultyComboBox = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        reserveSeatsTextField = new javax.swing.JTextField();
        reserveSubmitButton = new javax.swing.JButton();
        reserveStatusLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DateSpinner = new javax.swing.JSpinner();
        ResultLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addDatejButton = new javax.swing.JButton();
        AddDatejLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        DateforReservationjComboBox = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Room Scheduler");

        jLabel2.setText("Faculty Name: ");

        addFacultyTextField.setColumns(20);

        addFacultyButton.setText("Submit");
        addFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyButtonActionPerformed(evt);
            }
        });

        addFacultyStatusLabel.setText("    ");

        jLabel7.setText("   ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(addFacultyButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addFacultyStatusLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(addFacultyButton)
                .addGap(18, 18, 18)
                .addComponent(addFacultyStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Add Faculty", jPanel1);

        displayWaitlistButton.setText("Execute");
        displayWaitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayWaitlistButtonActionPerformed(evt);
            }
        });

        DisplayReservationsButton.setText("Execute ");
        DisplayReservationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayReservationsButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Display Reservations");

        jLabel5.setText("Display Waitlist");

        DateBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Select Date:");

        OutputTextArea.setColumns(20);
        OutputTextArea.setRows(5);
        jScrollPane1.setViewportView(OutputTextArea);

        javax.swing.GroupLayout DatesOfReservationComboboxLayout = new javax.swing.GroupLayout(DatesOfReservationCombobox);
        DatesOfReservationCombobox.setLayout(DatesOfReservationComboboxLayout);
        DatesOfReservationComboboxLayout.setHorizontalGroup(
            DatesOfReservationComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatesOfReservationComboboxLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(DatesOfReservationComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatesOfReservationComboboxLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatesOfReservationComboboxLayout.createSequentialGroup()
                        .addGroup(DatesOfReservationComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DatesOfReservationComboboxLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(DateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DatesOfReservationComboboxLayout.createSequentialGroup()
                                .addComponent(displayWaitlistButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DisplayReservationsButton)))
                        .addGap(72, 72, 72))))
            .addGroup(DatesOfReservationComboboxLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 116, Short.MAX_VALUE))
        );
        DatesOfReservationComboboxLayout.setVerticalGroup(
            DatesOfReservationComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatesOfReservationComboboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatesOfReservationComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(DatesOfReservationComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(DatesOfReservationComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayWaitlistButton)
                    .addComponent(DisplayReservationsButton))
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", DatesOfReservationCombobox);

        waitlistPanel.addTab("Status ", jTabbedPane1);

        jLabel10.setText("Room name:");

        jLabel13.setText("Number of seats:");

        RoomSeatsjTextField.setText("Please enter an integer value");

        AddRoomjButton.setText("Submit");
        AddRoomjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoomjButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Will display updates:");

        jLabel17.setText("If there is no new update to the reservations assume the waitlist was unchanged");

        AddRoomjTextArea.setColumns(20);
        AddRoomjTextArea.setRows(5);
        jScrollPane2.setViewportView(AddRoomjTextArea);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RoomNamejTextField1)
                            .addComponent(RoomSeatsjTextField)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(AddRoomjButton))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(RoomNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(RoomSeatsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(AddRoomjButton)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel18))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(45, 45, 45))
        );

        jTabbedPane2.addTab("", jPanel7);

        waitlistPanel.addTab("Add Room", jTabbedPane2);

        DropRoomjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Select Room:");

        jLabel19.setText("Will display updates:");

        DropRoomjButton.setText("Submit");
        DropRoomjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropRoomjButtonActionPerformed(evt);
            }
        });

        jLabel21.setText("If there was no new reservation assume the waitlist was unchanged");

        DropRoomjTextArea.setColumns(20);
        DropRoomjTextArea.setRows(5);
        jScrollPane3.setViewportView(DropRoomjTextArea);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DropRoomjButton)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(44, 44, 44)
                                    .addComponent(DropRoomjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel21)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel19))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DropRoomjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(30, 30, 30)
                .addComponent(DropRoomjButton)
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel21)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Drop Room", jPanel6);

        FacultyjComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DatejComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Select faculty:");

        jLabel16.setText("Select date:");

        CancelReservationJbutton.setText("Cancel Reservation");
        CancelReservationJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelReservationJbuttonActionPerformed(evt);
            }
        });

        jLabel20.setText("Will display updates:");

        CancelTextArea.setColumns(20);
        CancelTextArea.setRows(5);
        jScrollPane4.setViewportView(CancelTextArea);

        CancelWaitlistjButton.setText("Cancel Waitlist");
        CancelWaitlistjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelWaitlistjButtonActionPerformed(evt);
            }
        });

        jLabel22.setText("If nothing is displayed assume no new reservations were made");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(FacultyjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DatejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CancelReservationJbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CancelWaitlistjButton)
                                .addGap(95, 95, 95))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FacultyjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelReservationJbutton)
                    .addComponent(CancelWaitlistjButton))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(32, 32, 32))
        );

        waitlistPanel.addTab("Cancelations", jPanel3);

        jLabel23.setText("Display's selected faculty member's reservations and waitlist entrys.");

        FacultyStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel25.setText("Selecte faculty memeber:");

        Status2TextArea.setColumns(20);
        Status2TextArea.setRows(5);
        jScrollPane5.setViewportView(Status2TextArea);

        Status2jButton.setText("Submit");
        Status2jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Status2jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel23))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel25)
                        .addGap(67, 67, 67)
                        .addComponent(FacultyStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(Status2jButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FacultyStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(31, 31, 31)
                .addComponent(Status2jButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Status # 2", jPanel8);

        jLabel4.setText("Select Faculty: ");

        jLabel6.setText("Seats Required: ");

        reserveSeatsTextField.setColumns(3);

        reserveSubmitButton.setText("Submit Request");
        reserveSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSubmitButtonActionPerformed(evt);
            }
        });

        reserveStatusLabel.setText("   ");

        jLabel8.setText("Select Date:");

        DateSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1546362000000L), new java.util.Date(1546362000000L), new java.util.Date(1577725200000L), java.util.Calendar.DAY_OF_WEEK));

        ResultLabel.setText("Output");

        jLabel11.setText("Please use like a textfield");

        jLabel12.setText("MM/DD/YY format");

        addDatejButton.setText("add date ");
        addDatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDatejButtonActionPerformed(evt);
            }
        });

        AddDatejLabel.setText("Confirmation");

        jLabel24.setText("Select Date:");

        DateforReservationjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reserveStatusLabel)
                        .addGap(179, 179, 179)
                        .addComponent(ResultLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reserveSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(addDatejButton)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DateforReservationjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AddDatejLabel)))))
                            .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(reserveSubmitButton))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(DateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(addDatejButton)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(DateforReservationjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reserveSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(79, 79, 79)
                        .addComponent(reserveSubmitButton)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reserveStatusLabel)
                            .addComponent(ResultLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(AddDatejLabel)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Reserve Room", jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(37, Short.MAX_VALUE)
                        .addComponent(waitlistPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waitlistPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void DisplayReservationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayReservationsButtonActionPerformed
        ArrayList<ReservationEntry> reservations = new ArrayList();
        // code given by AL to convert string from combo box to sql date data type
        Date day = Date.valueOf(DateBox1.getSelectedItem().toString());
        reservations = ReservationQueries.ReservationsBydate(day);
        OutputTextArea.setText("FACULTY\tROOM\tDATE\tSEATS\tTIMESTAMP\t");
        SimpleDateFormat TSFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String text = "";
        for(int i= 0 ; i<reservations.size();i++){
            text = text+"\n"+reservations.get(i).getFaculty()+"\t"+reservations.get(i).getRoom()+"\t"+reservations.get(i).getDate().toString()+"\t"+String.valueOf(reservations.get(i).getSeats())
            +"\t"+TSFormat.format(reservations.get(i).getTimestamp());
        }
        OutputTextArea.setText(OutputTextArea.getText()+text);
    }//GEN-LAST:event_DisplayReservationsButtonActionPerformed

    private void displayWaitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayWaitlistButtonActionPerformed
        ArrayList<WaitlistEntry> waitlist = new ArrayList();
        waitlist = WaitlistQueries.getWaitlist();
        OutputTextArea.setText("FACULTY\tDATE\tSEATS\tTIMESTAMP\t");
        // placeholder
        String text = "";
        // convert timestamp  to string
        SimpleDateFormat TSFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        for(int i= 0; i <waitlist.size();i++){
            text = text+"\n"+waitlist.get(i).getFaculty()+"\t"+waitlist.get(i).getDate().toString()+"\t"+String.valueOf(waitlist.get(i).getSeats())+"\t"+TSFormat.format(waitlist.get(i).getTimestamp());
        }
        OutputTextArea.setText(OutputTextArea.getText()+text);
    }//GEN-LAST:event_displayWaitlistButtonActionPerformed

    private void reserveSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSubmitButtonActionPerformed
        String faculty;
        int seats;
        ArrayList<String> rooms = new ArrayList();// will store all rooms that satisfy seat requirement
        ArrayList<String> reserved = new ArrayList();// stores all reserved rooms

        // converts date from spinner into
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String comboxBoxValue = DateforReservationjComboBox.getSelectedItem().toString();
        Date day = Date.valueOf(comboxBoxValue);
        // addes date to db table "Dates" for reference
        // Dates.addDate(day); 
        // gets faculty value from combo box
        faculty = reserveFacultyComboBox.getSelectedItem().toString();
        // gets seats value from textfield
        seats = Integer.parseInt(reserveSeatsTextField.getText());

        rooms = RoomQueries.getAllPossibleRooms(seats);
        reserved = ReservationQueries.getReservationsByDate(day);
        
        reserve_comparison:
        for( int i = 0; i<rooms.size(); i++){

            //checks if room has already been reserved
            //if room isnt reserved make a reservation
            if(!reserved.contains(rooms.get(i)) ){
                ReservationQueries.addReservation(faculty,rooms.get(i), day, seats);
                ResultLabel.setText(faculty+" has reserved room "+rooms.get(i));
                break;
            }
            // all rooms have been checked so add faculty to waitlist
            else if(rooms.size() ==i+1){
                WaitlistQueries.addWaitlistEntry(faculty, day, seats);
                ResultLabel.setText(faculty+" has been put on the waitlist");
            }
        }
         if(rooms.size()==0){
         WaitlistQueries.addWaitlistEntry(faculty, day, seats);
         ResultLabel.setText(faculty+" has been put on the waitlist");
        }
    }//GEN-LAST:event_reserveSubmitButtonActionPerformed

    private void addFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyButtonActionPerformed
        // Add the faculty to the faculty table.
        String name = addFacultyTextField.getText();
        Faculty.addFaculty(name);
        addFacultyStatusLabel.setText(name+" has been added to the Faculty.");

        // rebuild the reservation faculty combo box.
        rebuildFacultyComboBoxes();
    }//GEN-LAST:event_addFacultyButtonActionPerformed

    private void AddRoomjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoomjButtonActionPerformed
        // TODO add your handling code here:
        AddRoomjTextArea.setText("");// resets text area
//add room similar he same as add faculty 
        String name = RoomNamejTextField1.getText();
        int seats  = Integer.parseInt(RoomSeatsjTextField.getText());
        RoomQueries.addRoom(name, seats);
        AddRoomjTextArea.setText("Room "+name+" has been added.");
        rebuildRoomComboBoxes();
        // must check waitlist to see if a room can be reserved for all dates in db
        ArrayList<String> dates = Dates.getAllDates();
        for(int i = 0; i<dates.size();i++){
       // converts the string to a date data type so it can be used in upcoming logic
            SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
            String date = dates.get(i);
            Date day =  Date.valueOf(date); // something missing?
        // below used in for loop
         ArrayList<WaitlistEntry> waitlist = WaitlistQueries.getWaitlistByDate(day);
        // logic to find waitlist entry that may reserve the newly added room
             for(int x = 0; x<waitlist.size();x++){
             // seats-> new room, checking if any seats request from waitlist can be satisified
             if(seats >= waitlist.get(x).getSeats()){
            //cancels waitlist entry 
              WaitlistQueries.cancelWaitlist(waitlist.get(x).getFaculty(), day);
            // Makes reservation with new room
            ReservationQueries.addReservation(waitlist.get(x).getFaculty(),name,day,waitlist.get(x).getSeats());
             AddRoomjTextArea.setText(AddRoomjTextArea.getText()+"\n"+waitlist.get(x).getFaculty()+" has reserved room "+name+" on "+dates.get(i)+".");
                break;     
                         }
                }
            }// end of both for loops
        // have a label saying that if no updates displayed then assume no new reservations
    }//GEN-LAST:event_AddRoomjButtonActionPerformed

    private void addDatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDatejButtonActionPerformed
        // TODO add your handling code here:
        // code from al to get date from spinnet
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(DateSpinner.getValue());
        Date day = Date.valueOf(spinnerValue);
        Dates.addDate(day);
        AddDatejLabel.setText(DateSpinner.getValue()+" has been added");
       // updates respective combo boxes
        rebuildDateComboBoxes(); 
    }//GEN-LAST:event_addDatejButtonActionPerformed

    private void DropRoomjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropRoomjButtonActionPerformed
        // TODO add your handling code here:
        DropRoomjTextArea.setText("");// resets text area
        String name = DropRoomjComboBox.getSelectedItem().toString();
        RoomQueries.dropRoom(name);
        rebuildRoomComboBoxes();// updates room comboboxes 
        // check reservations for all that had that room and try to find a room if possible otherwise waitlist them
       // list of reservation entry objects with the room that was just deleted  
        ArrayList<ReservationEntry> Reservations = ReservationQueries.getReservationByRoom(name); 
        ReservationQueries.cancelReservationByRoom(name);// all reservations under this room are now gone from the db
        //we must now decide if each of these reservations can find another room or go to the waitlist pretty much the same code as adding a reservation
        for(int x = 0; x<Reservations.size();x++){
            ArrayList <String >rooms = RoomQueries.getAllPossibleRooms(Reservations.get(x).getSeats());
            ArrayList <String> reserved = ReservationQueries.getReservationsByDate(Reservations.get(x).getDate());
        reserve_comparison:
        for( int i = 0; i<rooms.size(); i++){
            //checks if room has already been reserved
            //if room isnt reserved make a reservation
           if(!reserved.contains(rooms.get(i)) ){
                ReservationQueries.addReservation(Reservations.get(x).getFaculty(),rooms.get(i),Reservations.get(x).getDate(),Reservations.get(x).getSeats());
                DropRoomjTextArea.setText(DropRoomjTextArea.getText()+"\n"+Reservations.get(x).getFaculty()+" has reserved room "+rooms.get(i)+"on "+Reservations.get(x).getDate());
                break;
            }
            // all rooms have been checked so add faculty to waitlist
            else if(rooms.size() ==i+1){
                WaitlistQueries.addWaitlistEntry(Reservations.get(x).getFaculty(),Reservations.get(x).getDate(),Reservations.get(x).getSeats());
                DropRoomjTextArea.setText(DropRoomjTextArea.getText()+"\n"+Reservations.get(x).getFaculty()+" has been put on the waitlist");
            }
        }
     }
    }//GEN-LAST:event_DropRoomjButtonActionPerformed

    private void CancelReservationJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelReservationJbuttonActionPerformed
        // TODO add your handling code here:
        CancelTextArea.setText(""); // reset text area 
       String faculty =  FacultyjComboBox2.getSelectedItem().toString();
       Date date = Date.valueOf(DatejComboBox2.getSelectedItem().toString());
   
       // reservation entry is deleted from db
        ReservationQueries.cancelReservation(faculty, date);
        // check waitlist if any thing works 
        ArrayList <WaitlistEntry> waitlist = WaitlistQueries.getWaitlist();
        CancelTextArea.setText(faculty+"'s reservation has been canceled on "+DatejComboBox2.getSelectedItem().toString());
        for(int i = 0; i<waitlist.size();i++){
            ArrayList<String> rooms = RoomQueries.getAllPossibleRooms(waitlist.get(i).getSeats());
            ArrayList<ReservationEntry> reservations = ReservationQueries.ReservationsBydate(waitlist.get(i).getDate());
            for(int x = 0; x< rooms.size(); x++){
            if(!reservations.contains(rooms.get(x)) ){
                ReservationQueries.addReservation(waitlist.get(i).getFaculty(),rooms.get(i),waitlist.get(i).getDate(),waitlist.get(x).getSeats());
                WaitlistQueries.cancelWaitlist(waitlist.get(i).getFaculty(),waitlist.get(i).getDate());
                CancelTextArea.setText(CancelTextArea.getText()+"\n"+waitlist.get(i).getFaculty()+" has reserved room "+rooms.get(i)+" on "+DatejComboBox2.getSelectedItem().toString());                
            break;
            }
            // all rooms have been checked so add faculty to waitlist
            else if(rooms.size() ==i+1){
                WaitlistQueries.addWaitlistEntry(reservations.get(x).getFaculty(),reservations.get(x).getDate(),reservations.get(x).getSeats());
                CancelTextArea.setText(CancelTextArea.getText()+"\n"+waitlist.get(i).getFaculty()+" has been put on the waitlist");
                                        }
           //break;
            }
        }
    }//GEN-LAST:event_CancelReservationJbuttonActionPerformed

    private void CancelWaitlistjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelWaitlistjButtonActionPerformed
        // TODO add your handling code here:
        CancelTextArea.setText("");// clears text area
        String faculty =  FacultyjComboBox2.getSelectedItem().toString();
        Date date = Date.valueOf(DatejComboBox2.getSelectedItem().toString());
        WaitlistQueries.cancelWaitlist(faculty, date); //waitlist entry is deleted from db
        CancelTextArea.setText(faculty+"'s waitlist entry for "+DatejComboBox2.getSelectedItem().toString()+" has been canceled");
    }//GEN-LAST:event_CancelWaitlistjButtonActionPerformed

    private void Status2jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Status2jButtonActionPerformed
        // TODO add your handling code here:
        String faculty = FacultyStatusComboBox.getSelectedItem().toString();// gets faculty member from combobox
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationByFaculty(faculty); // gets list of reservations with that faculty member
        ArrayList<WaitlistEntry> waitlist = WaitlistQueries.getWaitlistbyFacutly(faculty);
        Status2TextArea.setText(faculty+"'s reservations displayed below:\n"+"ROOM\tDATE");
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        for(int i = 0; i < reservations.size();i++){
        Status2TextArea.setText(Status2TextArea.getText()+"\n"+reservations.get(i).getRoom()+"\t"+formater.format(reservations.get(i).getDate()));
        }
       String text = faculty+"'s waitlist entrys will be listed below \nSEATS\tDATE:";// place holder I don't feel like re-typing out Status2TextArea....
       for(int i = 0; i < waitlist.size(); i++){
       text = text+"\n"+String.valueOf(waitlist.get(i).getSeats())+"\t"+formater.format(waitlist.get(i).getDate());
       }
       Status2TextArea.setText(Status2TextArea.getText()+"\n"+text);
    }//GEN-LAST:event_Status2jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RoomSchedulerFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddDatejLabel;
    private javax.swing.JButton AddRoomjButton;
    private javax.swing.JTextArea AddRoomjTextArea;
    private javax.swing.JButton CancelReservationJbutton;
    private javax.swing.JTextArea CancelTextArea;
    private javax.swing.JButton CancelWaitlistjButton;
    private javax.swing.JComboBox DateBox1;
    private javax.swing.JSpinner DateSpinner;
    private javax.swing.JComboBox DateforReservationjComboBox;
    private javax.swing.JComboBox DatejComboBox2;
    private javax.swing.JPanel DatesOfReservationCombobox;
    private javax.swing.JButton DisplayReservationsButton;
    private javax.swing.JButton DropRoomjButton;
    private javax.swing.JComboBox DropRoomjComboBox;
    private javax.swing.JTextArea DropRoomjTextArea;
    private javax.swing.JComboBox FacultyStatusComboBox;
    private javax.swing.JComboBox FacultyjComboBox2;
    private javax.swing.JTextArea OutputTextArea;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JTextField RoomNamejTextField1;
    private javax.swing.JTextField RoomSeatsjTextField;
    private javax.swing.JTextArea Status2TextArea;
    private javax.swing.JButton Status2jButton;
    private javax.swing.JButton addDatejButton;
    private javax.swing.JButton addFacultyButton;
    private javax.swing.JLabel addFacultyStatusLabel;
    private javax.swing.JTextField addFacultyTextField;
    private javax.swing.JButton displayWaitlistButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox<String> reserveFacultyComboBox;
    private javax.swing.JTextField reserveSeatsTextField;
    private javax.swing.JLabel reserveStatusLabel;
    private javax.swing.JButton reserveSubmitButton;
    private javax.swing.JTabbedPane waitlistPanel;
    // End of variables declaration//GEN-END:variables
}
